name: MatterBridge Zigbee2MQTT
version: 0.0.24
slug: matterbridge-zigbee2mqtt
description: MatterBridge with Zigbee2MQTT plugin integration
url: https://github.com/l2jliga/ha-addons
codenotary: l2jliga@gmail.com
init: false
arch:
- i386
- amd64
- aarch64
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: Web UI
options:
  host: localhost
  port: 1883
  topic: zigbee2mqtt
  username: zigbee2mqtt
  password: zigbee2mqtt
  whiteList: []
  blackList: []
map:
- addon_config:rw
schema:
  host: str
  port: int
  topic: str
  username: str
  password: str
  whitelist:
  - str
  blacklist:
  - str
host_network: true
image: ghcr.io/l2jliga/matterbridge-zigbee2mqtt/{arch}
