name: MatterBridge Zigbee2MQTT
version: 1.6.0
slug: matterbridge-zigbee2mqtt
description: MatterBridge with Zigbee2MQTT plugin integration
url: https://github.com/l2jliga/ha-addons
codenotary: l2jliga@gmail.com
init: false
arch:
- i386
- amd64
- aarch64
ports:
  8283/tcp: null
  5550/tcp: null
  8284/tcp: null
webui: http://[HOST]:[PORT:8283]/
options:
  host: core-mosquitto
  port: 1883
  topic: zigbee2mqtt
  username: mqtt
  password: mqtt
  whiteList: []
  blackList: []
  switchList: []
  lightList: []
  outletList: []
  featureBlackList: []
  deviceFeatureBlackList: null
map:
- addon_config:rw
discovery:
- matter
panel_icon: mdi:bridge
panel_title: MatterBridge
schema:
  host: str
  port: int
  topic: str
  username: str
  password: str
  whitelist:
  - str?
  blacklist:
  - str?
  switchList:
  - str?
  lightList:
  - str?
  outletList:
  - str?
  featureBlackList:
  - str?
host_network: true
image: ghcr.io/l2jliga/matterbridge-zigbee2mqtt/{arch}
