name: MatterBridge Zigbee2MQTT
version: 1.4.1
slug: matterbridge-zigbee2mqtt
description: MatterBridge with Zigbee2MQTT plugin integration
url: https://github.com/l2jliga/ha-addons
codenotary: l2jliga@gmail.com
init: false
arch:
- i386
- amd64
- aarch64
ports:
  8283/tcp: 8283
ports_description:
  8283/tcp: Web UI
options:
  host: core-mosquitto
  port: 1883
  topic: zigbee2mqtt
  username: mqtt
  password: mqtt
  whiteList: []
  blackList: []
map:
- addon_config:rw
discovery:
- matter
ingress: true
ingress_port: 8283
panel_icon: mdi:bridge
panel_title: MatterBridge
schema:
  host: str
  port: int
  topic: str
  username: str
  password: str
  whitelist:
  - str?
  blacklist:
  - str?
host_network: true
image: ghcr.io/l2jliga/matterbridge-zigbee2mqtt/{arch}
